# CMake generated Testfile for 
# Source directory: /Users/andewx/Developer/Maketools/pbrt-v3/src/ext/glog
# Build directory: /Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(demangle "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Debug/demangle_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(demangle "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Release/demangle_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(demangle "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/MinSizeRel/demangle_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(demangle "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/RelWithDebInfo/demangle_unittest")
else()
  add_test(demangle NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(logging "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Debug/logging_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(logging "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Release/logging_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(logging "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/MinSizeRel/logging_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(logging "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/RelWithDebInfo/logging_unittest")
else()
  add_test(logging NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(signalhandler "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Debug/signalhandler_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(signalhandler "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Release/signalhandler_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(signalhandler "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/MinSizeRel/signalhandler_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(signalhandler "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/RelWithDebInfo/signalhandler_unittest")
else()
  add_test(signalhandler NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(stacktrace "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Debug/stacktrace_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(stacktrace "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Release/stacktrace_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(stacktrace "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/MinSizeRel/stacktrace_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(stacktrace "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/RelWithDebInfo/stacktrace_unittest")
else()
  add_test(stacktrace NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(stl_logging "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Debug/stl_logging_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(stl_logging "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Release/stl_logging_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(stl_logging "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/MinSizeRel/stl_logging_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(stl_logging "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/RelWithDebInfo/stl_logging_unittest")
else()
  add_test(stl_logging NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(symbolize "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Debug/symbolize_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(symbolize "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/Release/symbolize_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(symbolize "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/MinSizeRel/symbolize_unittest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(symbolize "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/glog/RelWithDebInfo/symbolize_unittest")
else()
  add_test(symbolize NOT_AVAILABLE)
endif()
