# CMake generated Testfile for 
# Source directory: /Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests
# Build directory: /Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(wtest "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/Debug/wtest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(wtest "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/Release/wtest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(wtest "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/MinSizeRel/wtest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(wtest "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/RelWithDebInfo/wtest")
else()
  add_test(wtest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(rtest "/Applications/CMake.app/Contents/bin/cmake" "-DOUT=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/rtest.out" "-DDATA=/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/Debug/rtest" "-P" "/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(rtest "/Applications/CMake.app/Contents/bin/cmake" "-DOUT=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/rtest.out" "-DDATA=/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/Release/rtest" "-P" "/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(rtest "/Applications/CMake.app/Contents/bin/cmake" "-DOUT=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/rtest.out" "-DDATA=/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/MinSizeRel/rtest" "-P" "/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(rtest "/Applications/CMake.app/Contents/bin/cmake" "-DOUT=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/rtest.out" "-DDATA=/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/RelWithDebInfo/rtest" "-P" "/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
else()
  add_test(rtest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ftest "/Applications/CMake.app/Contents/bin/cmake" "-DOUT=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/ftest.out" "-DDATA=/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/Debug/ftest" "-P" "/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ftest "/Applications/CMake.app/Contents/bin/cmake" "-DOUT=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/ftest.out" "-DDATA=/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/Release/ftest" "-P" "/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ftest "/Applications/CMake.app/Contents/bin/cmake" "-DOUT=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/ftest.out" "-DDATA=/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/MinSizeRel/ftest" "-P" "/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ftest "/Applications/CMake.app/Contents/bin/cmake" "-DOUT=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/ftest.out" "-DDATA=/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/RelWithDebInfo/ftest" "-P" "/Users/andewx/Developer/Maketools/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
else()
  add_test(ftest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(halftest "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/Debug/halftest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(halftest "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/Release/halftest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(halftest "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/MinSizeRel/halftest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(halftest "/Users/andewx/Developer/Maketools/pbrt-v3/xcode-build/src/ext/ptex/src/tests/RelWithDebInfo/halftest")
else()
  add_test(halftest NOT_AVAILABLE)
endif()
